apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-deployment
  labels:
    app: userManagement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userManagement-app
  template:
    metadata:
      labels:
        app: userManagement-app
    spec:
      containers:
        - name: usermanagement-deployment
          image: "usermanagement29387.azurecr.io/jamesaflukeusermanagement:24"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000