apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagementdeployment
  labels:
    app: userManagement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userManagementapp
  template:
    metadata:
      labels:
        app: userManagementapp
    spec:
      containers:
        - name: usermanagementdeployment
          image: hello-world
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000