apiVersion: apps/v1
kind: Deployment
metadata:
  name: userManagement-deployment
  labels:
    app: userManagement 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userManagement-app
  template:
    metadata:
      labels:
        app: userManagement-app
    spec:
      containers:
      - name: userManagement-deployment
        image: usermanagement29387.azurecr.io/jamesaflukeusermanagement:24
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000