apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: userManagement-service
spec:
 selector:
   # Selector for Pods
   app: userManagement-app
 ports:
   # Port Map
 - port: 80
   targetPort: 3000
   protocol: TCP
 type: LoadBalancer